#pragma once
/* Self-contained mobile UI; no CDN or persistent browser credential storage. */
static const char ADMIN_PAGE[] =
"<!doctype html>\n"
"<html lang=\"sl\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Nastavitve ventila</title>\n"
"<style>*{box-sizing:border-box}body{font:17px system-ui,sans-serif;background:#101b26;color:#eef3f7;margin:0;padding:20px}main{max-width:480px;margin:auto}h1{font-size:26px}h2{font-size:21px}form,section{background:#1d2d3d;padding:18px;border-radius:14px;margin:18px 0}label{display:block;margin:14px 0 6px}input,select,button{font:inherit;min-height:46px;width:100%;border-radius:8px;padding:10px;border:1px solid #94aabb}button{background:#9cdad3;color:#082b2a;margin-top:14px;font-weight:600;cursor:pointer}button:disabled{opacity:.55;cursor:wait}a{color:#a6e7ff}p{line-height:1.5}#message{white-space:pre-line}#issued-code{display:block;overflow-wrap:anywhere;font:20px monospace;padding:12px;background:#10212f}small{display:block;line-height:1.5}[hidden]{display:none!important}:focus-visible{outline:3px solid #ffe48b;outline-offset:3px}</style></head>\n"
"<body><main><h1>Nastavitve ventila</h1><p>Spremembe nastavitev ne odprejo vode.</p><p id=\"message\" role=\"status\" aria-live=\"polite\">Nalaganje …</p>\n"
"<div id=\"access\" hidden>\n"
"<form id=\"setup\" hidden><h2>Določite PIN</h2><p>Izberite štiri številke. Začetne ničle so dovoljene.</p><label>Nov PIN<input name=\"pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"new-password\" required></label><label>Ponovite PIN<input name=\"repeated_pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"new-password\" required></label><button>Določi PIN</button></form>\n"
"<form id=\"login\" hidden><h2>Prijava</h2><label>PIN<input name=\"pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"current-password\" required></label><button>Prijava</button><p><a href=\"#recover\" id=\"forgot\">Pozabljen PIN?</a></p></form>\n"
"<form id=\"recover\" hidden><h2>Obnova PIN-a</h2><p>Obnova ohrani nastavitve povezave, Wi-Fi in ventila.</p><label>Obnovitvena koda<input name=\"code\" type=\"password\" minlength=\"32\" maxlength=\"32\" pattern=\"[0-9a-f]{32}\" autocomplete=\"off\" required></label><label>Nov PIN<input name=\"pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"new-password\" required></label><label>Ponovite PIN<input name=\"repeated_pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"new-password\" required></label><button>Obnovi PIN</button></form>\n"
"</div>\n"
"<section id=\"recovery-once\" hidden><h2>Shranite obnovitveno kodo</h2><p>Koda je prikazana samo zdaj. Shranite jo na varno mesto. Prejšnja koda ne velja več.</p><code id=\"issued-code\"></code><button id=\"code-saved\">Kodo sem shranil/-a</button></section>\n"
"<div id=\"settings\" hidden><p id=\"confirmed\">Potrjene nastavitve se nalagajo …</p>\n"
"<form id=\"shower\"><h2>Tuš</h2><label>Trajanje tuša<select name=\"duration_minutes\"><option value=\"1\">1 minuta</option><option value=\"2\">2 minuti</option><option value=\"3\">3 minute</option><option value=\"4\">4 minute</option><option value=\"5\">5 minut</option><option value=\"6\">6 minut</option><option value=\"7\">7 minut</option><option value=\"8\">8 minut</option><option value=\"9\">9 minut</option><option value=\"10\">10 minut</option></select></label><small>Velja za naslednji tuš. Aktivni čas se ne spremeni.</small><button>Shrani trajanje</button></form>\n"
"<form id=\"rotation\"><h2>Zaslon</h2><label>Rotacija zaslona<select name=\"rotation_degrees\"><option value=\"0\">0°</option><option value=\"90\">90°</option><option value=\"180\">180°</option><option value=\"270\">270°</option></select></label><button>Shrani rotacijo</button></form>\n"
"<form id=\"pin\"><h2>Sprememba PIN-a</h2><label>Nov PIN<input name=\"pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"new-password\" required></label><label>Ponovite PIN<input name=\"repeated_pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"new-password\" required></label><button>Spremeni PIN</button></form>\n"
"<form id=\"recovery-code\"><h2>Nova obnovitvena koda</h2><label>Trenutni PIN<input name=\"pin\" type=\"password\" inputmode=\"numeric\" pattern=\"[0-9]{4}\" minlength=\"4\" maxlength=\"4\" autocomplete=\"current-password\" required></label><button>Izdaj novo kodo</button></form>\n"
"<form id=\"logout\"><button>Odjava</button></form><p><a href=\"/\">Povezave in Wi-Fi</a> · <a href=\"/valves-config\">Povezava z ventilom</a> · <a href=\"/ble\">Bluetooth</a></p></div>\n"
"<script>\n"
"'use strict';\n"
"const $=id=>document.getElementById(id);let csrf='',generation=null;\n"
"function message(text){$('message').textContent=text}\n"
"const errors={401:'Prijavite se s PIN-om.',403:'Zahteva ni dovoljena. Osvežite stran.',409:'Nastavitve so se spremenile. Preverite potrjene vrednosti in poskusite znova.',429:'Preveč poskusov. Počakajte 60 sekund.',503:'Nastavitve trenutno niso na voljo. Poskusite znova.',400:'Preverite vnos in ponovitev PIN-a.'};\n"
"async function api(path,data){const response=await fetch('/admin/api/'+path,{method:data?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:data?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(12000)});if(!response.ok){const error=new Error(errors[response.status]||'Zahteva ni uspela.');error.status=response.status;throw error}return response.json()}\n"
"function confirmed(value){generation=value.generation;$('confirmed').textContent='Potrjeno: '+value.duration_minutes+' min · '+value.rotation_degrees+'°';$('shower').elements.duration_minutes.value=value.duration_minutes;$('rotation').elements.rotation_degrees.value=value.rotation_degrees}\n"
"async function reloadSettings(){const value=await api('settings');confirmed(value)}\n"
"async function session(){const value=await api('session');csrf=value.csrf||'';$('access').hidden=value.authenticated;$('setup').hidden=!value.setup_required;$('login').hidden=value.setup_required;$('recover').hidden=true;$('settings').hidden=!value.authenticated;generation=null;if(value.authenticated)await reloadSettings()}\n"
"function issue(code){$('issued-code').textContent=code;$('recovery-once').hidden=false;$('access').hidden=true;message('Shranite novo obnovitveno kodo.')}\n"
"$('code-saved').onclick=async()=>{$('issued-code').textContent='';$('recovery-once').hidden=true;try{await session();message('Koda je shranjena.')}catch(e){message(e.message)}};\n"
"$('forgot').onclick=e=>{e.preventDefault();$('recover').hidden=false;$('login').hidden=true};\n"
"for(const form of document.forms)form.addEventListener('submit',async event=>{event.preventDefault();if(form.dataset.busy)return;const button=form.querySelector('button');form.dataset.busy='1';button.disabled=true;const op=form.id;const setting=op==='shower'||op==='rotation';try{\n"
" const data=Object.fromEntries(new FormData(form));if(setting){if(generation===null)throw new Error('Najprej ponovno naložite potrjene nastavitve.');data.generation=generation;for(const key of Object.keys(data))data[key]=Number(data[key])}\n"
" if(data.repeated_pin!==undefined&&data.pin!==data.repeated_pin)throw new Error('PIN-a se ne ujemata.');\n"
" const result=await api(op,data);if(setting){confirmed(result);message('Nastavitve so shranjene.')}else{form.reset();if(result.recovery_code){issue(result.recovery_code);if(op!=='recovery-code')$('settings').hidden=true}else{await session();message(op==='login'?'Prijavljeni ste.':'Sprememba je potrjena.')}}\n"
" }catch(error){let text=error.status?error.message:'Odgovor ni potrjen. '+error.message;if(setting){try{await reloadSettings();text+=' Prikazane so ponovno prebrane potrjene vrednosti.'}catch(e){generation=null;text+=' Ponovno branje ni uspelo. Osvežite stran.'}}message(text)}finally{delete form.dataset.busy;button.disabled=false}});\n"
"session().then(()=>message('')).catch(e=>message(e.message));\n"
"window.addEventListener('pagehide',()=>{$('issued-code').textContent='';$('recovery-once').hidden=true});\n"
"</script></main></body></html>\n"
;
static const char ADMIN_FORMS_JS[] =
"'use strict';\n"
"// Adapt existing forms to session-bound CSRF headers. No token is stored in HTML,\n"
"// a URL, or persistent browser storage. Forms fail closed without JavaScript.\n"
"document.addEventListener('submit',async event=>{\n"
" const form=event.target;if(!(form instanceof HTMLFormElement)||form.method.toUpperCase()!=='POST')return;\n"
" event.preventDefault();if(form.dataset.busy)return;\n"
" const action=new URL(form.action,location.href);if(action.origin!==location.origin)return;\n"
" const data=new URLSearchParams(new FormData(form));if(event.submitter?.name)data.append(event.submitter.name,event.submitter.value);\n"
" form.dataset.busy='1';const buttons=[...form.querySelectorAll('button,input[type=submit]')];buttons.forEach(b=>b.disabled=true);\n"
" try{\n"
"  const session=await fetch('/admin/api/session',{cache:'no-store',credentials:'same-origin',signal:AbortSignal.timeout(12000)});\n"
"  if(!session.ok)throw new Error('Prijava trenutno ni na voljo.');const state=await session.json();if(!state.authenticated){location.assign('/admin');return}\n"
"  const response=await fetch(action.href,{method:'POST',credentials:'same-origin',headers:{'X-CSRF-Token':state.csrf,'Content-Type':'application/x-www-form-urlencoded'},body:data,signal:AbortSignal.timeout(12000)});\n"
"  if(!response.ok)throw new Error('Shranjevanje ni potrjeno ('+response.status+'). Osvežite stran in preverite nastavitve.');\n"
"  if(response.redirected){location.assign(response.url);return}\n"
"  const html=await response.text();document.open();document.write(html);document.close();\n"
" }catch(error){let status=document.getElementById('admin-form-error');if(!status){status=document.createElement('p');status.id='admin-form-error';status.setAttribute('role','alert');form.append(status)}status.textContent='Odgovor ni potrjen. '+error.message}\n"
" finally{delete form.dataset.busy;buttons.forEach(b=>b.disabled=false)}\n"
"});\n"
;
